### ISSUE TITLE
data_process

### ISSUE THREAD

**Issue by Evelyn-zhou24** [weicy15/CGI#3]
**FileNotFoundError: [Errno 2] No such file or directory: 'data/douban/trusts.txt'**
“data_process处理过程中缺少trust.txt文件”

Traceback (most recent call last):
  File "D:\Code\CGI-main\data_process.py", line 138, in <module>
    data_process(dataset_name, split_rate=0.9, user_fre_threshold = 5, item_fre_threshold = 5, socia_data= True)
  File "D:\Code\CGI-main\data_process.py", line 90, in data_process
    social = pd.read_table(save_dir+"/trusts.txt", sep='\t', header= None, names= ['src', 'dst'])
  File "E:\learn\TensorFlow2\Anaconda\envs\PyTorch1.1\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "E:\learn\TensorFlow2\Anaconda\envs\PyTorch1.1\lib\site-packages\pandas\io\parsers\readers.py", line 683, in read_table
    return _read(filepath_or_buffer, kwds)
  File "E:\learn\TensorFlow2\Anaconda\envs\PyTorch1.1\lib\site-packages\pandas\io\parsers\readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "E:\learn\TensorFlow2\Anaconda\envs\PyTorch1.1\lib\site-packages\pandas\io\parsers\readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "E:\learn\TensorFlow2\Anaconda\envs\PyTorch1.1\lib\site-packages\pandas\io\parsers\readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "E:\learn\TensorFlow2\Anaconda\envs\PyTorch1.1\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "E:\learn\TensorFlow2\Anaconda\envs\PyTorch1.1\lib\site-packages\pandas\io\parsers\base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "E:\learn\TensorFlow2\Anaconda\envs\PyTorch1.1\lib\site-packages\pandas\io\common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'data/douban/trusts.txt'

**Comment by weicy15** [comment]
Hi, in fact, we don't use 'data/douban/trusts.txt' in the codes.

**Comment by weicy15** [comment]
Hi, in fact, we don't use "'data/douban/trusts.txt'" in the project. You can simply set "socia_data= False" in the function "data_process()".

**Comment by Evelyn-zhou24** [comment]
> 

Ok, thank you very much

**Comment by Evelyn-zhou24** [comment]
OK，thank you very much



---- Replied Message ----
| From | Chunyu ***@***.***> |
| Date | 08/12/2023 14:13 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [weicy15/CGI] data_process (Issue #3) |

Hi, in fact, we don't use "'data/douban/trusts.txt'" in the project. You can simply set "socia_data= False" in the function "data_process()".
